# Generated by Django 4.0.4 on 2022-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_catagory',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
    ]
