# Generated by Django 4.0.4 on 2022-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatagory', models.CharField(max_length=50)),
                ('catagoryid', models.IntegerField()),
            ],
        ),
    ]
