# Generated by Django 4.0.4 on 2022-07-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_firstname', models.CharField(max_length=30)),
                ('user_lastname', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_biography', models.TextField()),
                ('user_address', models.TextField()),
                ('user_doj', models.DateField()),
                ('user_image', models.ImageField(upload_to='pics')),
                ('user_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('user_posts', models.IntegerField(default=0)),
            ],
        ),
    ]
