# Generated by Django 4.0.4 on 2022-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_alter_usermanager_user_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='user_image',
            field=models.ImageField(default='avatar.jpg', upload_to='pics'),
        ),
    ]
