# Generated by Django 4.0.4 on 2022-07-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Contacts',
        ),
    ]
