# Generated by Django 4.0.4 on 2022-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_rename_main_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='readstatus',
            field=models.BooleanField(default=False),
        ),
    ]
