# Generated by Django 4.0.4 on 2022-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.CharField(max_length=100, default='-'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='main',
            name='twiter',
            field=models.CharField(max_length=100, default='-'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='main',
            name='youtube',
            field=models.CharField(max_length=100, default='-'),
            preserve_default=False,
        ),
    ]
