# Generated by Django 4.0.4 on 2022-05-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_main_name'),
        ('main', '0005_add_fields'),
    ]

    operations = [
    ]
