# Generated by Django 4.0.4 on 2022-05-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_0004_alter_main_name_0005_add_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='-', max_length=100)),
                ('twiter', models.CharField(default='-', max_length=100)),
                ('youtube', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='main',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='main',
            name='twiter',
        ),
        migrations.RemoveField(
            model_name='main',
            name='youtube',
        ),
    ]
