# Generated by Django 4.0.4 on 2022-05-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_social_remove_main_facebook_remove_main_twiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='twiter',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='youtube',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
