# Generated by Django 4.0.4 on 2022-05-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_main_facebook_main_twiter_main_youtube'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
