# Generated by Django 4.0.4 on 2022-05-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
