# Generated by Django 4.0.4 on 2022-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='title',
            field=models.CharField(max_length=50, default='-'),
            preserve_default=False,
        )
    ]
