# Generated by Django 4.0.4 on 2022-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_fields_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
