# Generated by Django 4.0.4 on 2022-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='email',
            field=models.EmailField(default='-'),
        ),

        migrations.AddField(
            model_name='main',
            name= 'contact',
            field=models.EmailField(default='-'),
        ),
    ]
